# Generated by Django 4.2.8 on 2024-07-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectimage_project_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
