# Generated by Django 4.2.8 on 2024-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_trailer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="download_label",
            field=models.CharField(blank=True, default="Download", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="download_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="external_label",
            field=models.CharField(blank=True, default="External Page", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="github_label",
            field=models.CharField(blank=True, default="GitHub", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="live_label",
            field=models.CharField(blank=True, default="Live Demo", max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
