# Generated by Django 4.2.8 on 2026-04-09 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_enable_rls_blog_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subscribe_all', models.BooleanField(default=True, help_text='Receive notifications for every new blog post.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('projects', models.ManyToManyField(blank=True, help_text='If not subscribed to all, only these projects trigger emails.', related_name='subscribers', to='projects.project')),
            ],
        ),
    ]
