# Generated by Django 4.2.8 on 2026-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_enable_rls_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Only live posts are visible on the site.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
